language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
services:
  - docker
env:
 - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
 - TF_VAR_AWS_REGION=$AWS_REGION
branches:
  only:
    - master
cache: bundler
before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user wheel
  - pip wheel awscli
  - pip install --user awscli
  - curl -o $HOME/.local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - chmod +x $HOME/.local/bin/ecs-cli
  - wget https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_amd64.zip -O /tmp/terraform.zip
  - unzip -d $HOME/.local/bin/ /tmp/terraform.zip
script: rake commit
notifications:
  email:
    on_success: change
    on_failure: always
